Repository Swipe-Jeju/swiping-jeju-frontend, pull requests merged in 2024-02, with the labels that each got.

#2 ✨Feat: 홈, 등록, 결과페이지
  .gitignore
  assets/images/icon/icon-kakao.png
  components/home/homeMapSelection/HomeMapSelection.jsx
  components/home/homeMapSelection/style.jsx
  components/home/homeStyleInput/HomeStyleInput.jsx
  components/layouts/Head.jsx
  components/layouts/Layout.jsx
  components/result/ResultHotplaceList.jsx
  components/result/ResultKakaoShareBtn.jsx
  package-lock.json
  package.json
  pages/_app.jsx
  pages/axios.js
  pages/home/Home.jsx
  pages/home/index.jsx
  pages/home/style.jsx
  pages/index.jsx
  pages/result/KakaoMap.jsx
  pages/result/Result.jsx
  pages/result/[id].jsx
  pages/result/style.jsx
Labels: size/XL, 🙋‍♂️ 희찬, ✨feature

#3 ✨Feat: 스와이프 페이지 기본 기능구현
  components/swiper/BackCard.jsx
  components/swiper/Card.jsx
  components/swiper/FrontCard.jsx
  package-lock.json
  package.json
  pages/_app.jsx
  pages/swiping/Swiping.jsx
  pages/swiping/index.jsx
  pages/swiping/style.jsx
  public/0.jpeg
  public/1.jpeg
  public/2.jpeg
  public/3.jpeg
  public/svg/close.svg
  public/svg/dislike.svg
  public/svg/like.svg
  public/svg/undo.svg
Labels: size/XL

#4 Design/home
  components/home/homeLading/HomeLanding.jsx
  components/home/homeLading/style.jsx
  components/home/homeMapSelection/HomeMapSelection.jsx
  components/home/homeMapSelection/style.jsx
  components/layouts/Layout.jsx
  components/result/ResultKakaoShareBtn.jsx
  pages/_app.jsx
  pages/home/index.jsx
  pages/home/style.jsx
  public/images/background/char_3.png
  public/images/background/char_green.png
  public/images/background/char_orange.png
  public/images/background/logo.png
  public/images/background/nocap.png
  public/images/jeju_map.png
Labels: size/L, 🙋‍♂️ 희찬, ✨feature

#5 ✨Feat: 커스텀 모달 추가 및 버튼 활성화 등을 위한 조건부 추가
  components/home/homeLading/HomeLanding.jsx
  components/modal/CustomModal.jsx
  components/swiper/BackCard.jsx
  components/swiper/Card.jsx
  components/swiper/FrontCard.jsx
  components/swiper/kakaoMap.jsx
  pages/home/index.jsx
  pages/swiping/index.jsx
  pages/swiping/style.jsx
  public/images/nav_logo.png
  public/svg/locationIcon.svg
  public/svg/pause.svg
Labels: size/XL, ✨feature

#7 ✨Feat: 로컬 벡터 데이터 베이스 구축 및 OPEN AI 구현
  .gitignore
  components/_styled/404Styled.jsx
  components/_styled/homeStyled.jsx
  components/_styled/resultStyled.jsx
  components/_styled/swipingStyled.jsx
  components/home/homeStyleInput/HomeStyleInput.jsx
  components/swiper/Card.jsx
  data/keywords.txt
  jsconfig.json
  package-lock.json
  package.json
  pages/api/get-keyword.js
  pages/home/index.jsx
  pages/index.jsx
  pages/notFound/404.jsx
  pages/notFound/index.jsx
  pages/result/KakaoMap.jsx
  pages/result/[id].jsx
  pages/style.jsx
  pages/swiping/index.jsx
  scripts/ingest-data-local.js
  templates/index.js
  utils/axios.js
  utils/combineDocument.js
  utils/getSplittedDocs.js
  utils/localRetriever.js
Labels: size/XL

#8 ✨Feat: 결과화면 제작
  assets/fonts/BagelFatOne-Regular.ttf
  assets/fonts/Font.css
  components/_styled/homeStyled.jsx
  components/_styled/resultStyled.jsx
  components/home/homeLading/HomeLanding.jsx
  components/home/homeLading/style.jsx
  components/layouts/Head.jsx
  components/result/ResultHotplaceList.jsx
  components/result/ResultKakaoShareBtn.jsx
  components/result/style.jsx
  pages/_app.jsx
  pages/result/KakaoMap.jsx
  pages/result/[id].jsx
  public/fonts/BagelFatOne.ttf
  public/images/share/facebook.png
  public/images/share/google.png
  public/images/share/kakao.png
  public/images/share/naver.png
Labels: size/XL
